// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"crud/adapters/inbound"
	"crud/adapters/inbound/api/controller"
	"crud/infra/persistence"
	"github.com/google/wire"
)

// Injectors from provider.go:

func InitializeAdapter() *inbound.InitialAdapter {
	database := persistence.SetupMongoDB()
	iProductDomainRepo := ProvideProductRepository(database)
	iProductService := ProductService(iProductDomainRepo)
	iProductController := ProvideProductServiceController(iProductService)
	initialAdapter := ProvideAdapter(iProductController)
	return initialAdapter
}

// provider.go:

func ProvideAdapter(
	ProductCtl controller.IProductController,
) *inbound.InitialAdapter {
	return inbound.NewInitialAdapter(ProductCtl)
}

var ProviderSet = wire.NewSet(
	ProvideAdapter,
	RepositoryProviderSet,
	ControllerProvideSet,
	ServiceProviderSet,
)
